version: '3.9'

services:
  model_pipeline:
    build: .
    container_name: model_pipeline
    volumes:
      - ./scripts:/workspace/scripts
      - ./data/input:/workspace/data/input
      - ./data/output:/workspace/data/output
      - ./data/tmp:/workspace/data/tmp
      - ./blender_mcp:/workspace/blender_mcp
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: ["python", "scripts/run_pipeline.py"]
    environment:
      - PYTHONPATH=/workspace
