version: "3.8"

services:
  model-generator:
    build: .
    container_name: model-generator
    ports:
      - "7860:7860"
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./app/models:/app/app/models
    environment:
      - MCP_ENDPOINT=http://host.docker.internal:3000
